#!/bin/bash
#
##########################################################
#  Dill 
#  System update utility for Arch-based Linux distros
#
#  Repository:
#    https://github.com/Pickles-Linux/pickles-update 
#       To be moved to own Repor after 1st Stable Release
#
#  Author:
#    Stu Pickles
#    https://github.com/Stu-Pickles3047
#               for
#   Pickles Linux
#   https://github.com/Pickles-Linux/
#
#  License:
#    The Unlicense
#
# -------------------------------------------------
#  Description:
#    An update helper for Pickles Linux.
#    Designed for Humor, and future growth.
#   Designed as a complete AUR Helper, removing the need for Paru, yay or alternatives
#   dill is designed to be modular for easy update, ease of addition of extra scripts etc.
#   
#   Rated R for Raunchy Aussie 
#
#  Script Purpose:
#    This script handles removing packages from the system.
#    Basically a wrapper for 'pacman -Rns'.
# -------------------------------------------------

# Source base utilities
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source "$SCRIPT_DIR/dill-base"

if [ -z "$1" ]; then
    error_log "Oi, what are ya tryin' to get rid of? Usage: dill remove <package-name>"
    exit 1
fi

for pkg in "$@"; do
    line_space
    # Ask for confirmation
    read -p "$(info_log "$(printf "$MSG_PROCEED_ACTION" "remove" "$pkg")")" -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
        info_log "$(printf "$MSG_REMOVE_START" "$pkg")"
        if sudo pacman -Rns --noconfirm "$pkg"; then
            success_log "$(printf "$MSG_REMOVE_SUCCESS" "$pkg")"
        else
            error_log "Bugger, it wouldn't let me kick it out. Check the error above."
        fi
    else
        warn_log "$MSG_REMOVE_CANCELLED"
    fi
done

exit 0
